zweb_data:
  image: busybox
  volumes:
    - /var/lib/postgresql

db:
  image: mariadb
  restart: always
  environment:
    MYSQL_DATABASE: zweb
    MYSQL_USER: zille
    DATABASE_PASSWORD: zille123
    MYSQL_ROOT_PASSWORD: zille123 
  ports:
    - "3306:3306"
  volumes_from:
    - zweb_data 

