zweb_data:
  restart: always
  image: busybox
  volumes:
    - /var/lib/mysql
  command: "true"

db:
  image: mariadb
  restart: always
  environment:
    MYSQL_DATABASE: zweb
    MYSQL_USER: zille
    DATABASE_PASSWORD: zille123
    MYSQL_ROOT_PASSWORD: zille123 
  ports:
    - "3306:3306"
  volumes_from:
    - zweb_data 

