# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180731_2154'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0006_auto_20171122_2224'),
        ('equipos', '0002_auto_20180731_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEquipo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', auto_now_add=True)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', auto_now=True)),
                ('dia', models.DateField(verbose_name='día')),
            ],
            options={
                'verbose_name': 'dia de asistencia de equipo a cc',
                'verbose_name_plural': 'dias de asistencias de equipo a cc',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAsistenciaEquipo',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('dia', models.DateField(verbose_name='día')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dia de asistencia de equipo a cc',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCostoEquipoValores',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('markup', models.DecimalField(verbose_name='Mark Up (%)', max_digits=18, decimal_places=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('equipo', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Equipos', db_constraint=False)),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valido_desde', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Periodo', db_constraint=False)),
            ],
            options={
                'verbose_name': 'historical valor de costo equipo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEquipoAlquiladoValores',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('alquiler', models.DecimalField(verbose_name='Desgastables + mano de obra + etc', max_digits=18, decimal_places=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('equipo', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Equipos', db_constraint=False)),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valido_desde', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Periodo', db_constraint=False)),
            ],
            options={
                'verbose_name': 'historical valor de equipo alquilado',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLubricantesValores',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('precio_filtro_aire', models.DecimalField(verbose_name='CU Filtro Aire', max_digits=18, decimal_places=3)),
                ('precio_filtro_combustible', models.DecimalField(verbose_name='CU Filtro Combustible', max_digits=18, decimal_places=3)),
                ('precio_filtro_hidraulico', models.DecimalField(verbose_name='CU Filtro Hidráulico', max_digits=18, decimal_places=3)),
                ('precio_filtro_lubricante', models.DecimalField(verbose_name='CU Filtro Lubricante', max_digits=18, decimal_places=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('equipo', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Equipos', db_constraint=False)),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valido_desde', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Periodo', db_constraint=False)),
            ],
            options={
                'verbose_name': 'historical valor de lubricante',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalManoObraValores',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('taller', models.DecimalField(verbose_name='taller', max_digits=18, decimal_places=2)),
                ('plataforma_combustible', models.DecimalField(verbose_name='plataforma de combustible', max_digits=18, decimal_places=2)),
                ('carretones', models.DecimalField(verbose_name='carretones', max_digits=18, decimal_places=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('equipo', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Equipos', db_constraint=False)),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valido_desde', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Periodo', db_constraint=False)),
            ],
            options={
                'verbose_name': 'historical valor de mano de obra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalParametrosGenerales',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('consumo_equipo_viales', models.DecimalField(verbose_name='consumo específico equipos viales (l/h/HP)', max_digits=5, decimal_places=3)),
                ('consumo_equipo_automotor', models.DecimalField(verbose_name='consumo específico equipos automotor (l/h/HP)', max_digits=5, decimal_places=3)),
                ('precio_gasoil', models.DecimalField(verbose_name='precio GO ($/l a granel sin impuestos deducibles)', max_digits=18, decimal_places=3)),
                ('precio_lubricante', models.DecimalField(verbose_name='precio lubricante $/l (a granel sin impuestos deducibles)', max_digits=18, decimal_places=3)),
                ('precio_hidraulico', models.DecimalField(verbose_name='precio fluido hidráulico (a granel sin impuestos deducibles)', max_digits=18, decimal_places=3)),
                ('horas_por_dia', models.IntegerField(verbose_name='horas por día', default=6)),
                ('dias_por_mes', models.IntegerField(verbose_name='días por mes', default=21)),
                ('horas_trabajo_anio', models.IntegerField(verbose_name='horas trabajo por año', default=1584)),
                ('valor_dolar', models.DecimalField(verbose_name='USD/$', max_digits=18, decimal_places=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valido_desde', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Periodo', db_constraint=False)),
            ],
            options={
                'verbose_name': 'historical parámetro general de taller',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPosesionValores',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('seguros', models.DecimalField(verbose_name='seguros', help_text='$/mes', max_digits=18, decimal_places=2)),
                ('ruta', models.DecimalField(verbose_name='R.U.T.A', help_text='$/mes', max_digits=18, decimal_places=2)),
                ('vtv', models.DecimalField(verbose_name='VTV', help_text='$/mes', max_digits=18, decimal_places=2)),
                ('certificacion', models.DecimalField(verbose_name='certificacion (IRAM)', help_text='$/mes', max_digits=18, decimal_places=2)),
                ('habilitaciones', models.DecimalField(verbose_name='habilitaciones', help_text='$/mes', max_digits=18, decimal_places=2)),
                ('rsv', models.DecimalField(verbose_name='RSV', help_text='$/mes', max_digits=18, decimal_places=2)),
                ('vhf', models.DecimalField(verbose_name='VHF', help_text='$/mes', max_digits=18, decimal_places=2)),
                ('impuestos', models.DecimalField(verbose_name='impuestos', help_text='$/mes', max_digits=18, decimal_places=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('equipo', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Equipos', db_constraint=False)),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valido_desde', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Periodo', db_constraint=False)),
            ],
            options={
                'verbose_name': 'historical valor de posesión',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistroAsistenciaEquipo',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('asistencia', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='equipos.AsistenciaEquipo', db_constraint=False)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Obras', db_constraint=False)),
                ('equipo', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Equipos', db_constraint=False)),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical registro de asistencia de equipo a cc',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReparacionesValores',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('equipo', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Equipos', db_constraint=False)),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valido_desde', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Periodo', db_constraint=False)),
            ],
            options={
                'verbose_name': 'historical valor de reparación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTrenRodajeValores',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', blank=True, db_index=True, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', blank=True, editable=False)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', blank=True, editable=False)),
                ('precio_neumatico', models.DecimalField(verbose_name='CU Neumático', max_digits=18, decimal_places=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Fecha de creación'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('equipo', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Equipos', db_constraint=False)),
                ('history_user', models.ForeignKey(null=True, related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valido_desde', models.ForeignKey(blank=True, null=True, related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Periodo', db_constraint=False)),
            ],
            options={
                'verbose_name': 'historical valor de tren de rodaje',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistenciaEquipo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación', auto_now_add=True)),
                ('modified_at', models.DateTimeField(verbose_name='Fecha de modificación', auto_now=True)),
                ('asistencia', models.ForeignKey(verbose_name='dia de asistencia', related_name='registros', to='equipos.AsistenciaEquipo')),
                ('centro_costo', models.ForeignKey(verbose_name='centro de costo', to='core.Obras')),
                ('equipo', models.ForeignKey(verbose_name='equipo', to='core.Equipos')),
            ],
            options={
                'verbose_name': 'registro de asistencia de equipo a cc',
                'verbose_name_plural': 'registros de asistencias de equipo a cc',
            },
        ),
    ]
