# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0021_auto_20170822_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costomanoobra',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='costomanoobra',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='costomanoobra',
            name='periodo',
        ),
        migrations.AlterUniqueTogether(
            name='costoposesion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='costoposesion',
            name='familia_equipo',
        ),
        migrations.RemoveField(
            model_name='costoposesion',
            name='periodo',
        ),
        migrations.AlterUniqueTogether(
            name='costosubcontrato',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='costosubcontrato',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='costosubcontrato',
            name='periodo',
        ),
        migrations.AlterUniqueTogether(
            name='lubricantefluidoshidro',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lubricantefluidoshidro',
            name='familia_equipo',
        ),
        migrations.RemoveField(
            model_name='lubricantefluidoshidro',
            name='periodo',
        ),
        migrations.AlterUniqueTogether(
            name='materialestotal',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='materialestotal',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='materialestotal',
            name='periodo',
        ),
        migrations.AlterUniqueTogether(
            name='reservereparaciones',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='reservereparaciones',
            name='familia_equipo',
        ),
        migrations.RemoveField(
            model_name='reservereparaciones',
            name='periodo',
        ),
        migrations.AlterUniqueTogether(
            name='servicioprestadoun',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='servicioprestadoun',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='servicioprestadoun',
            name='periodo',
        ),
        migrations.AlterUniqueTogether(
            name='trenrodaje',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='trenrodaje',
            name='familia_equipo',
        ),
        migrations.RemoveField(
            model_name='trenrodaje',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='costotipo',
            name='codigo',
            field=models.CharField(verbose_name='codigo', max_length=8, unique=True, help_text='Código único para identificar unívocamente el tipo de costo. Máximo largo: 8. Se removerán automáticamente espacios y se convertirá a mayúsculas.'),
        ),
        migrations.DeleteModel(
            name='CostoManoObra',
        ),
        migrations.DeleteModel(
            name='CostoPosesion',
        ),
        migrations.DeleteModel(
            name='CostoSubContrato',
        ),
        migrations.DeleteModel(
            name='LubricanteFluidosHidro',
        ),
        migrations.DeleteModel(
            name='MaterialesTotal',
        ),
        migrations.DeleteModel(
            name='ReserveReparaciones',
        ),
        migrations.DeleteModel(
            name='ServicioPrestadoUN',
        ),
        migrations.DeleteModel(
            name='TrenRodaje',
        ),
    ]
